name: elite_stocktaking
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nowa_runtime: ^0.1.0
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  collection: ^1.19.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
